export const GET_PLAYERS_SUCCESS = 'GET_PLAYERS_SUCCESS';
export const GET_PLAYERS_STARTED = 'GET_PLAYERS_STARTED';
export const GET_PLAYERS_FAILURE = 'GET_PLAYERS_FAILURE';

export const ADD_PLAYERS_SUCCESS = 'ADD_PLAYERS_SUCCESS';
export const ADD_PLAYERS_STARTED = 'ADD_PLAYERS_STARTED';
export const ADD_PLAYERS_FAILURE = 'ADD_PLAYERS_FAILURE';

export const DELETE_PLAYERS_SUCCESS = 'DELETE_PLAYERS_SUCCESS';
export const DELETE_PLAYERS_STARTED = 'DELETE_PLAYERS_STARTED';
export const DELETE_PLAYERS_FAILURE = 'DELETE_PLAYERS_FAILURE';

export const UPDATE_PLAYERS_SUCCESS = 'UPDATE_PLAYERS_SUCCESS';
export const UPDATE_PLAYERS_STARTED = 'UPDATE_PLAYERS_STARTED';
export const UPDATE_PLAYERS_FAILURE = 'UPDATE_PLAYERS_FAILURE';
